### ISSUE TITLE
Interface awdl0 does not have an IPv6 address.

### ISSUE THREAD

**Issue by mluis** [KishanBagaria/AirDoS#1]
Followed the README's instructions but it's getting the following under OSX 10.13:

```
$ python3 AirDoS.py 
2019-12-12 00:27:43,835 ⏳ Looking for devices... Open Finder -> AirDrop
Traceback (most recent call last):
  File "AirDoS.py", line 170, in <module>
    browser = AirDropBrowser(config)
  File "/usr/local/lib/python3.7/site-packages/opendrop/client.py", line 45, in __init__
    'Make sure that `owl` is running.'.format(config.interface))
RuntimeError: Interface awdl0 does not have an IPv6 address. Make sure that `owl` is running.
```

**Comment by KishanBagaria** [comment]
Seems to be related to https://github.com/seemoo-lab/opendrop/issues/22

Are you by any chance using non-standard network hardware?

**Comment by mluis** [comment]
No. I'm using 'en1' OSX wireless interface.

**Comment by KishanBagaria** [comment]
1. What do you see if you run `ifconfig awdl0`?
2. Can you try running `opendrop find`? The issues I linked above might've a fix.

**Comment by mluis** [comment]
The interface `awdl0` doesn't exist.
`opendrop find` returns the error stated above in the first comment.
The issues you stated seem to be using linux (?) or some kind of external wifi interface?

**Comment by KishanBagaria** [comment]
1. Did you try running owl like the error says?
2. Do you have another Mac running OS X 10.13 where you can check if it has the `awdl0`?

**Comment by mluis** [comment]
1. Yes.
2. No :(

**Comment by KishanBagaria** [comment]
Since this issue is more related to opendrop, you should post it [there](https://github.com/seemoo-lab/opendrop/issues/new) saying you can't run `opendrop find` because of that error. They may be better able to help.

**Comment by mluis** [comment]
Ok. Thank you
