### ISSUE TITLE
didnt work

### ISSUE THREAD

**Issue by matthewalan0** [KishanBagaria/AirDoS#3]
I am sorry, I installed all the required components, but it didnt work,please help me.

**Comment by KishanBagaria** [comment]
Can you elaborate? A screenshot or error messages you saw would be helpful in diagnosing this.

**Comment by PeterDragonTM** [comment]
Not sure if the OP os seeing the same thing as I. I instal the application, and then run "python3 AirDoS.py" after opening the Finder --> Airdrop. And despite phones being present on Firmware version prior to 13.1, the script does not detect a device. So far 3 different iPhones, 6, 8, and iPhone 5. 

I was trying this on 10.15.2, so I reinstalled macOS to the original version of 10.14.6, ad the same issue occurs. No error, just what's seen below. 

Tried with and with out sudo. 
$ sudo python3 ./AirDoS.py
2020-01-02 15:01:42,990 ⏳ Looking for devices... Open Finder -> AirDrop

$ python3 ./AirDoS.py
2020-01-02 15:01:42,990 ⏳ Looking for devices... Open Finder -> AirDrop

Any feedback is welcome

**Comment by KishanBagaria** [comment]
Can you try running `opendrop find` and see if that shows up any devices?

**Comment by PeterDragonTM** [comment]
It did return results there. See below. 

$ opendrop find
Looking for receivers. Press enter to stop ...
Found  index 0  ID 17xxxxxxxxx  name iPhone

**Comment by PeterDragonTM** [comment]
I also did the looping open drop, and that does work as well. 

$ while true; do opendrop send -r 0 -f requirements.txt; done
Asking receiver to accept ...
Receiver accepted
Uploading file ...
Uploading has been successful
Asking receiver to accept ...
Receiver accepted
Uploading file ...
Uploading has been successful
Asking receiver to accept ...
Receiver accepted
Uploading file ...
Uploading has been successful

**Comment by KishanBagaria** [comment]
Ah it seems opendrop was updated since this script was released and the latest version of opendrop has a breaking change 

This should make it work:
```
pip3 uninstall opendrop
pip3 install opendrop==0.10.3
```
I've tested this on Catalina so you can upgrade if you wish.

I'll commit a fix.

**Comment by Telistra** [comment]
Groovy!

$ python3 AirDoS.py
2020-01-02 15:35:14,888 ⏳ Looking for devices... Open Finder -> AirDrop
2020-01-02 15:35:19,634 ❌ Ignoring    iPhone                 iOS    13.3.0 ccxxxxxxxxxxxx-92af-4f2a-83f0-xxxxxxxxxxx7.local. [fe80::xxxxxxxxxxx]:8770

**Comment by ghost** [comment]
The problem I encountered has been solved. It should be the version of opendrop! Thank you very much!

**Comment by Floris497** [comment]
My iPhone automatically ignores the messages after 3 times declining.. so not very effective.

**Comment by KishanBagaria** [comment]
@Floris497 That's the fix Apple implemented in iOS 13.3 after I reported this. That's why the script automatically ignores devices with that iOS version.
